[project]
name = "generate-facturx-py"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "factur-x>=3.15",
    "flask>=3.1.0",
    "jinja2>=3.1.6",
]
